baseURL = 'https://mrguoxiaonotes.github.io/'
languageCode = 'zh-cn'
title = 'éƒ­å°å…ˆç”Ÿ | ä¿—é—»æ‰‹è®°'
content = "æˆ‘æ˜¯éƒ­å°å…ˆç”Ÿï¼Œä¸€ä½ç¤¾ä¼šè§‚å¯Ÿè€…å’Œè®°å½•è€…ã€‚è¿™é‡Œæ˜¯æˆ‘æ•´ç†å’Œå‘å¸ƒç¤¾ä¼šçºªå®ç±»æ–‡ç« çš„æ•°å­—ç©ºé—´ã€‚"
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
    identifier = "social"
    name = "ç¤¾ä¼šè§‚å¯Ÿ"
    url = "/social/"
    weight = 10

[[menu.main]]
    identifier = "life"
    name = "äººç”Ÿæ„Ÿæ‚Ÿ"
    url = "/life/"
    weight = 20

[[menu.main]]
    identifier = "lab"
    name = "å®éªŒå®¤"
    url = "/lab/"
    weight = 30

[[menu.main]]
    identifier = "about"
    name = "ğŸ‘¨ğŸ»â€ğŸ’» å…³äº"
    url = "/about/"
    weight = 40

[[menu.main]]
    identifier = "search"
    name = "ğŸ” æœç´¢"
    url = "/search/"
    weight = 50

[outputs]
    home = ["HTML", "RSS", "JSON"]